---
title: "Clean_PitchBook"
output: html_document
date: "2024-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## R Markdown
library(data.table)
library(dplyr)
library(haven)
library(stringr)
library(mvtnorm)
library(tidyr)
library(readxl)
library(stargazer)
library(readr)

options(scipen = 999)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

rm(list = ls())

# Read the dataset in the current folder (Excel)
data <- read_excel("../Data/Raw/PitchBook_All_Columns_DirectLending_2024_07_10.xlsx", skip = 8, col_names = TRUE)

# Split the Companies column into two columns based on the last ( and remove the last )
data <- data %>%
  separate(Companies, into = c("Company", "Company2"), sep = "\\(", remove = TRUE) %>%
  mutate(Company2 = str_remove(Company2, "\\)"))
# Order the dataset by Companies Company Company2
data <- data %>%
  select(Company, Company2, everything())
# In the column Company2, keep only the characters after : and remove the rest
data <- data %>%
  mutate(Company2 = str_remove(Company2, ".*:"))
# trim white spaces and then keep only the entries with less than or equal to 4 characters in Company2
data <- data %>%
  mutate(Company2 = str_trim(Company2)) %>%
  filter(nchar(Company2) <= 4)
# rename Company2 as Ticker
names(data)[2] <- "Ticker"
# Move variable Issue Date to the front
data <- data %>%
  select("Issue Date", everything())
# change issue date (numeric) to date format from Excel numbers using as.Date and first convert NA to 0
data <- data %>%
  mutate(`Issue Date` = ifelse(is.na(`Issue Date`), 0, `Issue Date`)) %>%
  mutate(`Issue Date` = as.Date(`Issue Date`, origin = "1899-12-30"))
# order Lenders, Net Income, and EBITDA to the front 
data <- data %>%
  select(Lenders, `Net Income`, EBITDA, `Deal Type 1`, everything())

# keep only US companies (those with company country/territory/region as United States)
data <- data %>%
  filter(`Company Country/Territory/Region` == "United States")

# clean Lender name (getting rid of *)
data <- data %>%
  mutate(Lenders = str_remove(Lenders, "\\*"))

# keep only the unique borrower name, ticker, and date of issue
deals <- data %>%
  distinct(Lenders, Company, Ticker, `Issue Date`)
# make sure each company-ticker-issue_date only has one observation in deals
deals <- deals %>%
  group_by(Company, Ticker, `Issue Date`) %>%
  filter(row_number() == 1) %>%
  ungroup()
write.csv(deals, "../Data/Cleaned/PitchBook_Cleaned.csv", row.names = FALSE)
```

```{r}
### Import and Analyze preliminary sample of 100 contracts ###
# Read the dataset in the current folder (Excel)
test_sample <- read_excel("../Data/Cleaned/Pitchbook_Cleaned_Aug7.xlsx", col_names = TRUE)

# change all variables besides the first 3 to be categorical (factor) variables that take 1 as long as the value is not NA
test_sample <- test_sample %>%
  mutate(across(-c(1:3), ~ ifelse(is.na(.), 0, 1)))

# generate Hard_N and Soft_N and Info_N that is the sum of monthly financial and budget forecast, sum of lender meetings and inspection, and sum of all respectively
test_sample <- test_sample %>%
  mutate(Hard_N = rowSums(select(test_sample, `Monthly Financial`:`Budget/Forecast`)),
         Soft_N = rowSums(select(test_sample, `Lender Meetings`:`Inspection`)),
         Info_N = rowSums(select(test_sample, `Monthly Financial`:`Inspection`)))

# generate the summary statistics for the sample 
summary(test_sample)
# change to data frame
test_sample <- as.data.frame(test_sample)
# output to latex table format (keep Monthly Financial, Budget/Forecast, Lender Meetings, Inspection, Hard_N, Soft_N, and Info_N) using stargazer and keep only the mean
stargazer(test_sample[, c(4:7)], type = "latex", summary.stat = "mean", digits = 2, title = "Summary Statistics of Sample", out = "../Results/Summary_Stats_Sample.tex")
# what's the correlation between the last 4 variables
cor(test_sample[, 4:7])

# number of zeros in each variable
colSums(test_sample != 0)
```

```{r}
### Merge the Cleaned sample with the original dataset for names and other information ###
# merge lender names from deals and to test_sample using Company Ticker and Issue Date as keys
# Change Isssue Date format of test_sample to date
test_sample <- test_sample %>%
  mutate(`Issue Date` = as.Date(`Issue Date`))
inner_join <- left_join(test_sample, deals, by = c("Ticker", "Issue Date"))
# order lender and company.y to the front
inner_join <- inner_join %>%
  select(Lenders, everything())
```

```{r}
# Import Compustat Quarterly from Raw folder
compustat <- fread("../Data/Raw/2023-24_Compustat_Annual.csv")
# Keep only 2021 observations
compustat <- compustat %>%
  filter(fyear == 2023) %>% filter(tic != "") %>% filter(!is.na(at))
# for each ticker, only keep that with the largest at
compustat <- compustat %>%
  group_by(tic) %>%
  filter(row_number() == which.max(at))

# Merge the compustat data with the test sample data using the Ticker as the key
test_compustat_joined <- inner_join %>%
  left_join(compustat, by = c("Ticker" = "tic"))

# Output summary statistics (mean, p25, median, p75, min, max for assets, revenues, ebitda, liabilities, and working capital using stargazer (make sure that the test_compustat_joined is a df)

test_compustat_joined <- as.data.frame(test_compustat_joined)
# Define custom labels for the variables
variable_labels <- c("Total Assets", "EBIT", "EBITDA", "Total Liabilities", "Total Revenue", "Working Capital")

stargazer(test_compustat_joined[, c(25:30)], type = "latex", summary.stat = c("min", "p25", "median", "p75", "max", "mean"), digits = 2, covariate.labels = variable_labels, title = "Summary Statistics of Sample with Compustat Data", out = "../Results/Summary_Stats_Sample_Compustat.tex")

```